language: node_js
node_js:
  - "stable"
notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  npm start

deploy:
  provider: heroku
  skip_cleanup: true
  github-token: travis
  local_dir: build
  on:
    branch: main